//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishermanApp.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishermanApp.Resources.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Catch.
        /// </summary>
        public static string AddCatchEvent {
            get {
                return ResourceManager.GetString("AddCatchEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add More Catch Data.
        /// </summary>
        public static string AddMoreCatchData {
            get {
                return ResourceManager.GetString("AddMoreCatchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Another Row.
        /// </summary>
        public static string AddRow {
            get {
                return ResourceManager.GetString("AddRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SPECIES OF BAIT :.
        /// </summary>
        public static string BaitSpecie {
            get {
                return ResourceManager.GetString("BaitSpecie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF BAIT : .
        /// </summary>
        public static string BaitType {
            get {
                return ResourceManager.GetString("BaitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYCATCH : .
        /// </summary>
        public static string Bycatch {
            get {
                return ResourceManager.GetString("Bycatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain : .
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to catch data cannot be empty.
        /// </summary>
        public static string CatchDataCannotBeEmpty {
            get {
                return ResourceManager.GetString("CatchDataCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATCH DETAILS :.
        /// </summary>
        public static string CatchDetails {
            get {
                return ResourceManager.GetString("CatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATCH SPECIES SELECTION.
        /// </summary>
        public static string CatchSpeciesSelection {
            get {
                return ResourceManager.GetString("CatchSpeciesSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DEAD.
        /// </summary>
        public static string Dead {
            get {
                return ResourceManager.GetString("Dead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⮟.
        /// </summary>
        public static string DownArrow {
            get {
                return ResourceManager.GetString("DownArrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Fishing.
        /// </summary>
        public static string EndSet {
            get {
                return ResourceManager.GetString("EndSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Ship.
        /// </summary>
        public static string EndTrip {
            get {
                return ResourceManager.GetString("EndTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START TRIP.
        /// </summary>
        public static string FlyoutStartTrip {
            get {
                return ResourceManager.GetString("FlyoutStartTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGTH OF GANGION : .
        /// </summary>
        public static string GangionLength {
            get {
                return ResourceManager.GetString("GangionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEAR : .
        /// </summary>
        public static string Gear {
            get {
                return ResourceManager.GetString("Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEAR SELECTION.
        /// </summary>
        public static string GearSelection {
            get {
                return ResourceManager.GetString("GearSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS OFF.
        /// </summary>
        public static string GpsOff {
            get {
                return ResourceManager.GetString("GpsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS STATUS : .
        /// </summary>
        public static string GpsStatus {
            get {
                return ResourceManager.GetString("GpsStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Port : .
        /// </summary>
        public static string HomePort {
            get {
                return ResourceManager.GetString("HomePort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOOKS PER BASKET :.
        /// </summary>
        public static string HooksPerBasket {
            get {
                return ResourceManager.GetString("HooksPerBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TYPE OF HOOK : .
        /// </summary>
        public static string HookType {
            get {
                return ResourceManager.GetString("HookType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev.norpacexport.com:8076/.
        /// </summary>
        public static string Hostname {
            get {
                return ResourceManager.GetString("Hostname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string IndicatorLoading {
            get {
                return ResourceManager.GetString("IndicatorLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNET STATUS : .
        /// </summary>
        public static string InternetStatus {
            get {
                return ResourceManager.GetString("InternetStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your vessel identification.
        /// </summary>
        public static string LinkVesselTextHeader {
            get {
                return ResourceManager.GetString("LinkVesselTextHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Example: J1-1234-AA).
        /// </summary>
        public static string LinkVesselTextHeaderExample {
            get {
                return ResourceManager.GetString("LinkVesselTextHeaderExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        public static string Live {
            get {
                return ResourceManager.GetString("Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Your Vessel.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENGTH OF LONGLINE : .
        /// </summary>
        public static string LongLineLength {
            get {
                return ResourceManager.GetString("LongLineLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longlines.
        /// </summary>
        public static string Longlines {
            get {
                return ResourceManager.GetString("Longlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc Gear.
        /// </summary>
        public static string MiscGear {
            get {
                return ResourceManager.GetString("MiscGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nets.
        /// </summary>
        public static string Nets {
            get {
                return ResourceManager.GetString("Nets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Pending Data To Upload.
        /// </summary>
        public static string NoDataToUpload {
            get {
                return ResourceManager.GetString("NoDataToUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Trip Recorded For The Date Selected.
        /// </summary>
        public static string NoTripsToDisplay {
            get {
                return ResourceManager.GetString("NoTripsToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find Vessel Record.
        /// </summary>
        public static string NoVesselRecord {
            get {
                return ResourceManager.GetString("NoVesselRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NUMBER OF BASKETS : .
        /// </summary>
        public static string NumberOfBaskets {
            get {
                return ResourceManager.GetString("NumberOfBaskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFLINE.
        /// </summary>
        public static string Offline {
            get {
                return ResourceManager.GetString("Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ONLINE.
        /// </summary>
        public static string Online {
            get {
                return ResourceManager.GetString("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity : .
        /// </summary>
        public static string Quanity {
            get {
                return ResourceManager.GetString("Quanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUANTITY : .
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dev.norpacexport.com:8086/.
        /// </summary>
        public static string RemoteAppHostName {
            get {
                return ResourceManager.GetString("RemoteAppHostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J1-1234-AA.
        /// </summary>
        public static string SampleId {
            get {
                return ResourceManager.GetString("SampleId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET DETAILS.
        /// </summary>
        public static string SetDetails {
            get {
                return ResourceManager.GetString("SetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SET NUMBER : .
        /// </summary>
        public static string SetNumber {
            get {
                return ResourceManager.GetString("SetNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send an SOS signal using your phone flashlight.
        /// </summary>
        public static string SosLabel {
            get {
                return ResourceManager.GetString("SosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGNAL SOS.
        /// </summary>
        public static string SosSignal {
            get {
                return ResourceManager.GetString("SosSignal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species : .
        /// </summary>
        public static string Species {
            get {
                return ResourceManager.GetString("Species", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Begin Fishing.
        /// </summary>
        public static string StartSet {
            get {
                return ResourceManager.GetString("StartSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depart Dock.
        /// </summary>
        public static string StartTrip {
            get {
                return ResourceManager.GetString("StartTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Start Coordinates.
        /// </summary>
        public static string TripCoordinates {
            get {
                return ResourceManager.GetString("TripCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Duration.
        /// </summary>
        public static string TripDuration {
            get {
                return ResourceManager.GetString("TripDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip End Coordinates.
        /// </summary>
        public static string TripEndCoordinates {
            get {
                return ResourceManager.GetString("TripEndCoordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip End Time.
        /// </summary>
        public static string TripEndTime {
            get {
                return ResourceManager.GetString("TripEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIP HISTORY.
        /// </summary>
        public static string TripHistory {
            get {
                return ResourceManager.GetString("TripHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Start Time.
        /// </summary>
        public static string TripStartTime {
            get {
                return ResourceManager.GetString("TripStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Tracker.
        /// </summary>
        public static string TripTracker {
            get {
                return ResourceManager.GetString("TripTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troll and Pole.
        /// </summary>
        public static string TrollAndPole {
            get {
                return ResourceManager.GetString("TrollAndPole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn Off SOS Signal.
        /// </summary>
        public static string TurnSosOff {
            get {
                return ResourceManager.GetString("TurnSosOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On SOS Signal.
        /// </summary>
        public static string TurnSosOn {
            get {
                return ResourceManager.GetString("TurnSosOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Complete.
        /// </summary>
        public static string UploadComplete {
            get {
                return ResourceManager.GetString("UploadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD DATA.
        /// </summary>
        public static string UploadData {
            get {
                return ResourceManager.GetString("UploadData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Name : .
        /// </summary>
        public static string VesselName {
            get {
                return ResourceManager.GetString("VesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Catch Details.
        /// </summary>
        public static string ViewCatchDetails {
            get {
                return ResourceManager.GetString("ViewCatchDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Effort Details.
        /// </summary>
        public static string ViewEffortDetails {
            get {
                return ResourceManager.GetString("ViewEffortDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View On Map.
        /// </summary>
        public static string ViewOnMap {
            get {
                return ResourceManager.GetString("ViewOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER.
        /// </summary>
        public static string WeatherForecast {
            get {
                return ResourceManager.GetString("WeatherForecast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
